/*
 * Copyright (C) 2016 Ernesto Serrano <info at ernesto.es>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package smm;

import java.awt.Cursor;
import sm.esc.graphics.Config;
import sm.esc.ui.CanvasImage;

/**
 * Esta clase representa una ventana interna
 * @author Ernesto Serrano
 */
public class InternalWindow extends javax.swing.JInternalFrame
{

    private MainWindow parent;

    /**
     * Creates new form VentanaInterna
     */
    public InternalWindow()
    {
        initComponents();
    }

    /**
     *
     * @return
     */
    public CanvasImage getCanvas()
    {
        return this.canvas;
    }

    /**
     * Establece el padre de la ventana
     * @param w la instancia de MainWindow
     */
    public void setParent(MainWindow w)
    {
        this.parent = w;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane = new javax.swing.JScrollPane();
        canvas = new sm.esc.ui.CanvasImage();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(600, 400));

        canvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                canvasMouseMoved(evt);
            }
        });
        canvas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                canvasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jScrollPane.setViewportView(canvas);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Controla cuando el ratón ha entrado en el lienzo para pintar la posición
     * @param evt el evento del ratón
     */
    private void canvasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseMoved

        this.parent.setCursorPosition("(" + evt.getX() + "," + evt.getY() + ")");

        if (Config.GENERALCONFIG.getSelectedTool() == Config.Tool.HAND)
            this.setCursor(new Cursor(java.awt.Cursor.MOVE_CURSOR));
        else
            this.setCursor(new Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

    }//GEN-LAST:event_canvasMouseMoved
    
    /**
     * Controla cuando el ratón ha salido del lienzo para dejar de pintar la posición
     * @param evt el evento del ratón
     */
    private void canvasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseExited
        this.parent.setCursorPosition("(x,y)");
        this.setCursor(new Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_canvasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.esc.ui.CanvasImage canvas;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
